name: Skaffold Image
on: 
  push:
    paths:
    - 'skaffold/**' 
    - '.github/workflows/skaffold.yml'
jobs:
  build-push: 
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Build skaffold image
      run: docker build ./skaffold --file ./skaffold/Dockerfile --build-arg version=${VERSION} --tag docker.pkg.github.com/anarcher/images/skaffold:${VERSION}
    - name: Push skaffold image
      run: docker push docker.pkg.github.com/anarcher/images/skaffold:${VERSION}
    env: 
      VERSION: v0.39.0
